name: Lighthouse CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lighthouse:
    name: Run Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.10.x
      - name: Run Lighthouse CI
        run: |
          lhci autorun \
            --upload.target=temporary-public-storage \
            --collect.url=https://weirdmenim.github.io/my-portfolio/